### ISSUE TITLE
Pass deployment of "test software to argocd"

### ISSUE THREAD

**Issue by urmas-villem** [urmas-villem/ClusterEye#30]

**Comment by urmas-villem** [comment]
This is my argoapp:
https://github.com/urmas-villem/ClusterEye/blob/main/kubernetes/Testsoftware/argoapp/testsoftware-setup.yaml
```
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: testsoftware
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/urmas-villem/ClusterEye.git
    targetRevision: HEAD
    path: kubernetes/Testsoftware/deployments
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
```

This tells ArgoCD to recursively go through the directory kubernetes/Testsoftware/deployments and render all applications it finds.

This is my deployments directory: https://github.com/urmas-villem/ClusterEye/tree/main/kubernetes/Testsoftware/deployments
Currently i have prometheus, alertmanager and logstash in here. These are just deployed so my application has something to read when deployed. If my application is in an empty cluster it wont display any results.
